<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Alt Text' => '',
    'Application environment whether development, stage or production' => '',
    'Description' => '',
    'Description for the site' => '',
    'Meta Description' => '',
    'Meta Keywords' => '',
    'Meta description for the site' => '',
    'Meta keywords for the site' => '',
    'Minimum 3 characters' => '',
    'Name of the site' => '',
    'Spaces not allowed. Allowed characters [a-zA-Z0-9_-]' => '',
];
