<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add To Cart' => '',
    'Add to Cart' => '',
    'Back' => '',
    'Billing Details' => '',
    'Checkout' => '',
    'Confirm Order' => '',
    'Continue Shopping' => '',
    'Customer should agree to terms and conditions for the purchase' => '',
    'Delivery Options' => '',
    'Edit Cart' => '',
    'Incomplete Order' => '',
    'Input quantity should be >= 1' => '',
    'Input quantity should be >= minimum quantity' => '',
    'Item' => '',
    'Payment Method' => '',
    'Payment methods are not enabled. Please contact admin to enable payment methods.' => '',
    'Shipping methods are not enabled. Please contact admin to enable shipping methods.' => '',
    'Shopping Cart' => '',
    'Thank you for placing order with us. In case of any query, please contact us back' => '',
    'The order is incomplete.' => '',
    'View Cart' => '',
    'Your shopping cart is empty!' => '',
];
