<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All Customers' => '',
    'Billing Address' => '',
    'Creating an account will make your shopping a nice experience. It would make your order management and tracking much friendly.' => '',
    'Customer' => '',
    'Customer Activity' => '',
    'Customer Group' => '',
    'Customer Groups' => '',
    'Customer Metadata' => '',
    'Customer Notified' => '',
    'Customer Online' => '',
    'Customer Service' => '',
    'Customers' => '',
    'Date Added' => '',
    'Default Address' => '',
    'Edit Profile' => '',
    'Enter the e-mail address associated with your account. Click submit to have your information e-mailed to you.' => '',
    'Forgot Password Request' => '',
    'I am a returning customer' => '',
    'Latest Customers' => '',
    'Manage Customer Groups' => '',
    'Manage Customers' => '',
    'My Account' => '',
    'My Downloads' => '',
    'New Customer' => '',
    'New Customer Registration' => '',
    'Notify Customer' => '',
    'Register Account' => '',
    'Returning Customer' => '',
    'Shipping Address' => '',
    'Status' => '',
    'added a new address.' => '',
    'created a new order.' => '',
    'guest' => '',
    'logged in.' => '',
    'registered for an account.' => '',
    'requested a new password.' => '',
    'updated their account details.' => '',
    'updated their account password.' => '',
];
