<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Code' => '',
    'Configuration Data' => '',
    'Copy Files' => '',
    'Copy Folders' => '',
    'Delete Files' => '',
    'Enhancements' => '',
    'Extension' => '',
    'Extension Summary' => '',
    'Extensions' => '',
    'Index' => '',
    'Installer' => '',
    'Manage Extensions' => '',
    'Manager Others Extension' => '',
    'Modifications' => '',
    'Modified Files' => '',
    'Modules' => '',
    'Operations' => '',
    'Overview' => '',
    'Payment Methods' => '',
    'Shipping Methods' => '',
    'Source File' => '',
    'Source Folder' => '',
    'Sql' => '',
    'Sqls' => '',
    'Target Folder' => '',
    'The content is empty' => '',
    'The data is missing' => '',
    'The expression is not found in line {line}' => '',
    'Upload Extension' => '',
    'install.php file is missing in the zip folder' => '',
    'install.php has invalid configuration' => '',
];
