<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '"allow_url_include" should be disabled at php.ini' => '',
    '"expose_php" should be disabled at php.ini' => '',
    '"safe_mode" should be disabled at php.ini' => '',
    'Adding instance data successfull' => '',
    'Application Rebuild' => '',
    'Back up database starts' => '',
    'Back up database successfull' => '',
    'Begin Installation' => '',
    'Configuration file is missing' => '',
    'Configuration files created successfully' => '',
    'Configuration saved successfully' => '',
    'Create tables for module ke is successful' => '',
    'Database Host' => '',
    'Database Name' => '',
    'Database Password' => '',
    'Database Port' => '',
    'Database Username' => '',
    'Database creation successfull' => '',
    'Default data added for module ke' => '',
    'Demo data added for module ke' => '',
    'Development' => '',
    'Either GD PHP extension with FreeType support or ImageMagick PHP extension with PNG support is required for image CAPTCHA.' => '',
    'GD extension should be installed with FreeType support in order to be used for image CAPTCHA.' => '',
    'If you have the database created with username and password, no need to provide admin username and password. Please provide correct database credentials.' => '',
    'Imagick extension should be installed with PNG support in order to be used for image CAPTCHA.' => '',
    'Install Demo Data' => '',
    'Installation Output' => '',
    'Installation completed sucessfully' => '',
    'Instructions' => '',
    'Keywords' => '',
    'Logo' => '',
    'Mcrypt extension' => '',
    'Memo' => '',
    'Module permissions loaded successfully' => '',
    'My Demo Site Description' => '',
    'My Demo Site Keywords' => '',
    'Name' => '',
    'PHP mail SMTP server required' => '',
    'Please take up the backup of database if existing database is used' => '',
    'Populate database admin username and password if you are using a new database and application would create it.' => '',
    'Pre-Installation Check' => '',
    'Production' => '',
    'Remove tables from database' => '',
    'Required By' => '',
    'Required for MySQL database.' => '',
    'Restart' => '',
    'Result' => '',
    'Set time limit for execution to' => '',
    'Staging' => '',
    'Start building database' => '',
    'Start loading module permissions' => '',
    'Start writing configuration file' => '',
    'Super user created successfully' => '',
    'System Settings' => '',
    'The database does not exist or the user does not exist ' => '',
    'There was a problem assigning the previliges to the user on database thi' => '',
    'There was a problem creating the database' => '',
    'There was a problem creating the user ' => '',
    'Well done! You have installed the application successfully.' => '',
];
