<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Default from address of the system user sending the email.' => '',
    'Default from name of the system user sending the email.' => '',
    'Default reply to address in the system.' => '',
    'Notification Key' => '',
    'SMTP Host' => '',
    'SMTP Password' => '',
    'SMTP Port' => '',
    'SMTP Username' => '',
    'Sending Method' => '',
    'Subject for the email' => '',
    'Test email address' => '',
    'Type of notification' => '',
    'Use SMTP Authentication' => '',
];
