<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Content' => '',
    'Data' => '',
    'Default Subject' => '',
    'Enable test mode' => '',
    'Enable test mode where notification data would be stored in log tables in database.' => '',
    'From Address' => '',
    'From Name' => '',
    'High' => '',
    'Identity Name' => '',
    'Identity Type' => '',
    'Layout' => '',
    'Layouts' => '',
    'List All' => '',
    'Low' => '',
    'Mail' => '',
    'Manage Layouts' => '',
    'Manage Notifications' => '',
    'Manage Templates' => '',
    'Medium' => '',
    'Module Name' => '',
    'Notification' => '',
    'Notification Layout' => '',
    'Notifications' => '',
    'Notify Key' => '',
    'Permission' => '',
    'Priority' => '',
    'Reply To Address' => '',
    'SMTP' => '',
    'SMTP Host' => '',
    'SMTP Password' => '',
    'SMTP Port' => '',
    'SMTP Username' => '',
    'Send Date Time' => '',
    'Sending Method' => '',
    'Status' => '',
    'Template' => '',
    'Template Preview' => '',
    'Templates' => '',
    'Test Email Address' => '',
    'The notification template is missing for key: {key}' => '',
    'Type' => '',
    'Use SMTP Authentication' => '',
];
