<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add History' => '',
    'Add Order History' => '',
    'Add Payment' => '',
    'Amount' => '',
    'Bill To' => '',
    'Cancelled' => '',
    'Cancelled Reversal' => '',
    'Chargeback' => '',
    'Comments' => '',
    'Complete Order' => '',
    'Completed' => '',
    'Date Added' => '',
    'Denied' => '',
    'Expired' => '',
    'Failed' => '',
    'Incomplete Order' => '',
    'Input Quantity should be >= minimum quantity' => '',
    'Invalid order' => '',
    'Invoice' => '',
    'Invoice Number:' => '',
    'Invoice thi' => '',
    'Invoices' => '',
    'Issue Date:' => '',
    'Latest Orders' => '',
    'Manage Orders' => '',
    'My Orders' => '',
    'Net Payment' => '',
    'New Order Created' => '',
    'Order' => '',
    'Order Address' => '',
    'Order Completion' => '',
    'Order Details' => '',
    'Order History' => '',
    'Order Id' => '',
    'Order Number:' => '',
    'Order Payment' => '',
    'Order Payment Transaction Map' => '',
    'Order Payments' => '',
    'Order Product' => '',
    'Order Products' => '',
    'Order could not be updated.' => '',
    'Orders' => '',
    'Paid amount can not be greater than the pending amount' => '',
    'Paid amount should be greater than 0' => '',
    'Payment Details' => '',
    'Payment Method:' => '',
    'Payment Type' => '',
    'Pending' => '',
    'Previous' => '',
    'Processed' => '',
    'Processing' => '',
    'Product Details' => '',
    'Received Order' => '',
    'Refunded' => '',
    'Reversed' => '',
    'Select Payment Method' => '',
    'Ship To' => '',
    'Shipped' => '',
    'Shipping' => '',
    'Shipping Address' => '',
    'Terms' => '',
    'The transaction is saved successfully' => '',
    'Total Including Tax' => '',
    'Total Items' => '',
    'Transaction Record' => '',
    'Unique Id' => '',
    'Update Order' => '',
    'View Cart' => '',
    'View Invoice' => '',
    'Voided' => '',
];
