<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Payment' => '',
    'Amount' => '',
    'Captured Amount' => '',
    'Cash Details' => '',
    'Cash On Delivery' => '',
    'Cash On Delivery Settings' => '',
    'Cash On Delivery Transaction' => '',
    'Cash On Delivery Transactions' => '',
    'Charge' => '',
    'Default order status' => '',
    'Manage Enhancements' => '',
    'Manage Extensions' => '',
    'Manage Modifications' => '',
    'Manage Modules' => '',
    'Manage Payments' => '',
    'Order' => '',
    'Payment Method' => '',
    'Payment Status' => '',
    'Payment Type' => '',
    'Payments' => '',
    'Paypal Settings' => '',
    'Paypal Standard' => '',
    'Pending Amount' => '',
    'Private Key' => '',
    'Public Key' => '',
    'Received Date' => '',
    'Select Payment Method' => '',
    'Stripe' => '',
    'Stripe Settings' => '',
    'Stripe Transaction' => '',
    'Stripe Transactions' => '',
    'Total Amount' => '',
    'Transaction Fee' => '',
    'Transaction ID' => '',
    'View Payments' => '',
];
