<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A random code for the product.' => '',
    'Alias for Product' => '',
    'Categories for the Product' => '',
    'European Article Number' => '',
    'Height for the product' => '',
    'If you want to emphasize the most important products, the Featured Products is exactly what you need.' => '',
    'Initial stock for the product' => '',
    'International Standard Book Number' => '',
    'Japanese Article Number' => '',
    'Length for the product' => '',
    'Manufacturer Part Number' => '',
    'Meta Description for Product' => '',
    'Meta Keywords for Product' => '',
    'Minimum Quantity required to add product to the cart.' => '',
    'Model for Product' => '',
    'Name for Product' => '',
    'Price for Product' => '',
    'Price of the shipping' => '',
    'Select "Out of Stock", "In Stock" as the message shown on the product page when the product quantity reaches 0.' => '',
    'Subtract Stock by the purchase quantity for e.g. If there are 100 laptops, and 2 items are purchased, stock would be reduced to 98.' => '',
    'Tags associated with the product. e.g - Useful Products' => '',
    'Universal Product Code' => '',
    'Width for the product' => '',
];
