<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Calculate handling fees type fixed or percent' => '',
    'Comments associated with the shipping' => '',
    'Handling Fee, fixed or percent. If percent for example 6% equals .06' => '',
    'Method name for shipping. It could be Fixed or Plus Handling as suitable' => '',
    'Shipping Method' => '',
    'Shipping fee' => '',
    'Specific zones to which the shipping is applied' => '',
    'Type of flat rate i.e per order, per item or none' => '',
    'Zones to which the shipping would be applied. All zones or specific zones.' => '',
];
