<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Allow checkout if item is not in stock' => '',
    'Allow customers to checkout without creating an account. This will not be available when a downloadable product is in the shopping cart.' => '',
    'Allow guests to post reviews.' => '',
    'Allow reviews on the product page' => '',
    'Allow store to display compare products' => '',
    'Allow store to display wishlist' => '',
    'Change the default currency. Clear your browser cache to see the change and reset your existing cookie.' => '',
    'Country for the store' => '',
    'Data Category associated with the store. The entities for example products associated with the datacategory would be associated to the store.' => '',
    'Default Customer Group' => '',
    'Determines how many catalog items are shown per page (products, categories, etc).' => '',
    'Discount amount customer will get per point.' => '',
    'Display Prices With Tax' => '',
    'Display dimensions of product.' => '',
    'Display stock quantity on the product page.' => '',
    'Display weight of product.' => '',
    'In the list view, short description character limit (categories, special etc).' => '',
    'Is store default for the application' => '',
    'Language for the store' => '',
    'Length Class for the store' => '',
    'Name of the store' => '',
    'Set the default order status when an order is processed.' => '',
    'Set the invoice prefix (e.g. USNI). Invoice IDs will start at 1 for each unique prefix.' => '',
    'Show out of stock warning if item is not in stock' => '',
    'State for the store' => '',
    'Theme for this store' => '',
    'Timezone in which store operates' => '',
    'Track customers online via the customer reports section.' => '',
    'Web url for the store' => '',
    'Weight Class for the store' => '',
];
