<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activate/Deactivate' => '',
    'Allow Compare Products' => '',
    'Allow Guest Reviews' => '',
    'Allow Reviews' => '',
    'Allow Wishlist' => '',
    'Allow out of stock checkout' => '',
    'Cart Image Height' => '',
    'Cart Image Width' => '',
    'Category' => '',
    'Category Image Height' => '',
    'Category Image Width' => '',
    'Compare Image Height' => '',
    'Compare Image Width' => '',
    'Customer Online' => '',
    'Customer Prefix' => '',
    'Data category associated to selected store is not active. Please contact system admin.' => '',
    'Default' => '',
    'Default Customer Group' => '',
    'Default Store' => '',
    'Display Dimensions' => '',
    'Display Price With Tax' => '',
    'Display Stock' => '',
    'Display Weight' => '',
    'Guest Checkout' => '',
    'Icon' => '',
    'Image' => '',
    'Images' => '',
    'Invalid Order' => '',
    'Invoice Prefix' => '',
    'Is Default' => '',
    'List Description  Limit' => '',
    'Local' => '',
    'Manage Stores' => '',
    'Number of items per page for catalog' => '',
    'Order Prefix' => '',
    'Product List Image Height' => '',
    'Product List Image Width' => '',
    'Related Product Image Height' => '',
    'Related Product Image Width' => '',
    'Selected store is not active. Please contact system admin.' => '',
    'Set as default' => '',
    'Settings' => '',
    'Show out of stock warning' => '',
    'Store' => '',
    'Store Image Height' => '',
    'Store Image Width' => '',
    'Store Logo' => '',
    'Store Url' => '',
    'Stores' => '',
    'Tax Calculation Based On' => '',
    'This is test store set up with the application' => '',
    'Wishlist Image Height' => '',
    'Wishlist Image Width' => '',
];
