<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account' => '',
    'Activate' => '',
    'Address' => '',
    'Address first line' => '',
    'Address second line' => '',
    'Address1' => '',
    'Address2' => '',
    'Addresses' => '',
    'CPanel Login' => '',
    'Change Others Password' => '',
    'Change Password' => '',
    'Change Status' => '',
    'Confirm Password' => '',
    'Confirm your email account' => '',
    'Database Admin Password' => '',
    'Database Admin User Name' => '',
    'Deactivate' => '',
    'Edit Profile' => '',
    'Email' => '',
    'Email Address' => '',
    'First Name' => '',
    'Forgot Password' => '',
    'Forgot Password Request' => '',
    'Full Name' => '',
    'Last Login' => '',
    'Last Login IP' => '',
    'Last Name' => '',
    'Latest Users' => '',
    'Login' => '',
    'Logout' => '',
    'Manage Users' => '',
    'Mobile' => '',
    'My Account' => '',
    'My Profile' => '',
    'Name' => '',
    'New Password' => '',
    'New User Registration' => '',
    'Notifications' => '',
    'Office Phone' => '',
    'Owner' => '',
    'Password' => '',
    'Password token expiry' => '',
    'Person' => '',
    'Person Details' => '',
    'Phone Number' => '',
    'Please confirm your email by clicking the link below to activate your account.' => '',
    'Postal Code' => '',
    'Profile' => '',
    'Profile Image' => '',
    'Register' => '',
    'Related Id' => '',
    'Related Model' => '',
    'Remember me' => '',
    'Same As Billing Address' => '',
    'Sign In' => '',
    'Status for the address i.e. if it is valid or not.' => '',
    'Super User Email' => '',
    'Super User Password' => '',
    'Super Username' => '',
    'The credentials passed are not valid.' => '',
    'Timezone' => '',
    'User' => '',
    'User Settings' => '',
    'Username' => '',
    'Users' => '',
    'You have changed your password' => '',
    'Your account is not active. Kindly contact system admin.' => '',
    'Your email has been validated, Please login to continue.' => '',
    'Your email validation fails. Please contact system admin.' => '',
];
