<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<div class="notifications">
                                                    <ul>
                                                        <li>Must contains one digit from 0-9</li>
                                                        <li>Must contains one alphabet(case insensitive)</li>
                                                        <li>Must contains one special symbol</li>
                                                        <li>Match anything with previous condition checking
                                                                {6,20} length at least 6 characters and maximum of 20</li>
                                                    </ul>
                                                </div>' => '',
    'Password has been changed successfully.' => '',
    'The given email is not registered with us. Please enter a valid email.' => '',
    'User settings are saved successfully.' => '',
    'You have successfully registered with the system. An activation email has been sent at your registered email address.' => '',
    'Your account is not in active status.' => '',
    'Your login credentials are sent on registered email address.' => '',
];
